influxdata/influxdata-docker

- telegraf/1.0/alpine/Dockerfile
If `ca-certificates` is missing, `telegraf` can't deal with `https`, ex:
ERROR in input [haproxy]: Errors encountered: [Unable to connect to haproxy server 'https://foo.com/haproxy?stats/;csv': Get https://foo.com/haproxy?stats/;csv: x509: failed to load system roots and no roots provided]
> [telegraf:alpine] Keep `ca-certificates` installed in image

- influxdb/1.1/alpine/Dockerfile
It was never supposed to be exposed, but it got copied from the main
image before that port was removed from the main image during initial
development.
Now that the admin interface is deprecated and isn't on by default,
there's even less of a reason for it to be exposed.
> Remove port 8083 from the exposed ports in influxdb alpine

- telegraf/1.1/alpine/Dockerfile
- telegraf/1.2/alpine/Dockerfile
added iputils to the top level so ping -i works.
for version 1.2.1
(i will update the 1.1 branch next.)
> fix for ping -i

- influxdb/1.1/alpine/Dockerfile
- influxdb/1.2/alpine/Dockerfile
- kapacitor/1.1/alpine/Dockerfile
- kapacitor/1.2/alpine/Dockerfile
- telegraf/1.1/alpine/Dockerfile
- telegraf/1.2/alpine/Dockerfile
This will cause the alpine images to resolve DNS using /etc/hosts along
with the normal DNS resolver.
Fixes #76.
> Write /etc/nsswitch.conf in the alpine images

- chronograf/1.3/Dockerfile
Container goes from ~200MB to ~100MB
This fixes #87
> Update chronograf Dockerfile to use jessie-slim.

- chronograf/1.3/alpine/entrypoint.sh
- chronograf/1.3/entrypoint.sh
The path is now set to /var/lib/chronograf/chronograf-v1.db by default.
This should be inside of the default volume automatically. It is also
possible to override the path using an environment variable or the
command line option.
Fixes #97.
> Set the boltdb path for chronograf

- telegraf/1.2/Dockerfile
- telegraf/1.2/alpine/Dockerfile
- telegraf/1.3/Dockerfile
- telegraf/1.3/alpine/Dockerfile
Include net-snmp-tools package to Alpine container as it is needed by SNMP Telegraf plugin.
MIB lookups and proper SNMP table support require utilities "snmptranslate" and "snmptable" which are available in this package.
> Add net-snmp-tools (snmp) package to Telegraf containers.

- influxdb/1.2/alpine/init-influxdb.sh
- influxdb/1.2/init-influxdb.sh
- influxdb/1.3/alpine/init-influxdb.sh
- influxdb/1.3/init-influxdb.sh
- influxdb/nightly/alpine/init-influxdb.sh
- influxdb/nightly/init-influxdb.sh
The current init script fails to initialize the database when the container is started with `INFLUXDB_HTTP_HTTPS_ENABLED=true` as no `-ssl` flag is passed to the `influx` tool in this case.
This PR changes the init script to set `INFLUXDB_HTTP_HTTPS_ENABLED=false` when starting the temporary `influxd` which is only used during initialization. This avoid having to figure out whether `-unsafeSsl` is need in addition to `-ssl` for self-signed certificates.
> Disable SSL during InfluxDB initialization

- influxdb/1.3/Dockerfile
- influxdb/1.3/alpine/Dockerfile
Reverts back to the <= 1.3.5 way of extracting the static tarball, now
that 1.3.7 restores that packaging layout.
> Update for influxdb 1.3.7

- chronograf/1.3/alpine/Dockerfile
- influxdb/1.3/alpine/Dockerfile
- influxdb/1.4/alpine/Dockerfile
- influxdb/nightly/alpine/Dockerfile
- kapacitor/1.2/alpine/Dockerfile
- kapacitor/1.3/alpine/Dockerfile
- telegraf/1.3/alpine/Dockerfile
- telegraf/1.4/alpine/Dockerfile
Updates all Alpine Linux images to the latest version (3.6). Tested running the `./circle-test.sh` script from the project root.
> Upgrade base Alpine Linux images to 3.6

- influxdb/1.3/alpine/init-influxdb.sh
- influxdb/1.3/init-influxdb.sh
- influxdb/1.4/alpine/init-influxdb.sh
- influxdb/1.4/init-influxdb.sh
- influxdb/nightly/alpine/init-influxdb.sh
- influxdb/nightly/init-influxdb.sh
Relax bootstrapping check in `init-influxdb.sh` to allow for /var/lib/
influxdb being a mount point.
If this script is generated, please point me to its source repo and I
can make a PR there instead.
Closes #163
> Relax bootstrapping check

- chronograf/1.3/alpine/Dockerfile
- chronograf/1.4/alpine/Dockerfile
- influxdb/1.3/Dockerfile
- influxdb/1.3/alpine/Dockerfile
- influxdb/1.3/data/Dockerfile
- influxdb/1.3/data/alpine/Dockerfile
- influxdb/1.3/meta/Dockerfile
- influxdb/1.3/meta/alpine/Dockerfile
- influxdb/1.4/Dockerfile
- influxdb/1.4/alpine/Dockerfile
- influxdb/nightly/Dockerfile
- influxdb/nightly/alpine/Dockerfile
- kapacitor/1.3/Dockerfile
- kapacitor/1.3/alpine/Dockerfile
- kapacitor/1.4/Dockerfile
- kapacitor/1.4/alpine/Dockerfile
- telegraf/1.4/Dockerfile
- telegraf/1.4/alpine/Dockerfile
- telegraf/1.5/Dockerfile
- telegraf/1.5/alpine/Dockerfile
`--no-verbose` disables the progress bar without also removing error
messages and basic information. This is much better for debugging
without flooding the terminal with the progress data.
> Switch all instances of `wget -q` to `wget --no-verbose`

- chronograf/1.5/alpine/Dockerfile
- chronograf/1.6/alpine/Dockerfile
- chronograf/1.7/alpine/Dockerfile
- influxdb/1.5/alpine/Dockerfile
- influxdb/1.5/data/alpine/Dockerfile
- influxdb/1.5/meta/alpine/Dockerfile
- influxdb/1.6/alpine/Dockerfile
- influxdb/1.6/data/alpine/Dockerfile
- influxdb/1.6/meta/alpine/Dockerfile
- influxdb/1.7/alpine/Dockerfile
- influxdb/1.7/data/alpine/Dockerfile
- influxdb/1.7/meta/alpine/Dockerfile
- influxdb/nightly/alpine/Dockerfile
- kapacitor/1.4/alpine/Dockerfile
- kapacitor/1.5/alpine/Dockerfile
- telegraf/1.10/alpine/Dockerfile
- telegraf/1.8/alpine/Dockerfile
- telegraf/1.9/alpine/Dockerfile
Alpine 3.8 has a vulnerable version of Busybox.
We need to update to version >= 1.30.1 to receive
the relevant security patches.
Alpine 3.9 has the patched version of Busybox.
busybox version 1.28.4-r0 updated to >= 1.30.1
busybox
update to version >= 1.30.1
vulnarabilities:
high CVE-2018-20679 https://nvd.nist.gov/vuln/detail/CVE-2018-20679
high CVE-2019-5747 https://nvd.nist.gov/vuln/detail/CVE-2019-5747
> upgrade: Alpine 3.9 for vulnerability patches

- telegraf/1.10/alpine/Dockerfile
- telegraf/1.8/alpine/Dockerfile
- telegraf/1.9/alpine/Dockerfile
Without `tzdata` package, configuring `grok_timezone` report errors like below:
```
2019-03-22T17:27:24Z I! Starting Telegraf 1.10.0
2019-03-22T17:27:24Z I! Using config file: /etc/telegraf/telegraf.conf
2019-03-22T17:27:24Z W! improper timezone supplied (Asia/Shanghai), setting loc to UTC
...
2019-03-22T17:27:24Z E! [telegraf] Error running agent: location: Asia/Shanghai could not be loaded as a location
```
> Install tzdata in telegraf alpine images

- chronograf/1.6/alpine/Dockerfile
- chronograf/1.7/alpine/Dockerfile
- chronograf/1.8/alpine/Dockerfile
- influxdb/1.7/alpine/Dockerfile
- influxdb/1.8/alpine/Dockerfile
- influxdb/nightly/alpine/Dockerfile
- kapacitor/1.4/alpine/Dockerfile
- kapacitor/1.5/alpine/Dockerfile
- telegraf/1.12/alpine/Dockerfile
- telegraf/1.13/alpine/Dockerfile
- telegraf/1.14/alpine/Dockerfile
As recommended by the Docker images team, use `gpgconf --kill all` to close all components running as daemons before we attempt to remove the ~/.gnupg directory.  This should avoid possible errors removing the directory.
I have tested the build of Telegraf 1.14 image.
ref: https://github.com/docker-library/official-images/pull/8159#issuecomment-641573393
> Shutdown gpg background tasks in alpine image

- kapacitor/1.5/Dockerfile
- kapacitor/1.5/alpine/Dockerfile
This will update the kap docker build to 1.5.6
> chore: kapacitor build to 1.5.6

- influxdb/2.0/alpine/Dockerfile
- influxdb/2.0/alpine/default-config.yml
- influxdb/2.0/alpine/entrypoint.sh
- influxdb/test/test-2x-e2e.sh
Extracted from #442
Based on #445 for now, to make the diff reasonable.
This adds the files needed to build `influxdb:2.0-alpine`, and extends the e2e test logic to cover both builds.
> Add influxdb 2.0 alpine image.

- influxdb/1.8/Dockerfile
- influxdb/1.8/alpine/Dockerfile
Purposefully not updating the enterprise `data` and `meta` images since that binary hasn't been fully tested yet.
> Bump InfluxDB 1.x to 1.8.4

- influxdb/2.0/alpine/entrypoint.sh
- influxdb/2.0/entrypoint.sh
Closes #471
1. Instead of `ping`-ing an arbitrary number of times and bailing out, `ping` as long as the PID for `influxd` is still running. This should prevent premature shutdowns of servers that take awhile to boot up for the first time.
2. Don't bother spinning up the "init" instance of `influxd` if there's no logic to run against it. This should shave some time off initial boot-up and prevent the upgrade-timeout-clean loop users have been seeing.
I believe this "fixes" the `rm` issue mentioned in the linked issue by avoiding the code-path entirely. We were previously `rm`-ing files out of the engine directory of the running `influxd` process when startup took too long, and (I think) were seeing the effects of `influxd` concurrently writing files into directories the shell was trying …
> Fix ping-until-startup logic for InfluxDB 2.x

- influxdb/2.0/alpine/entrypoint.sh
- influxdb/2.0/entrypoint.sh
- influxdb/test/cases/test-help
Closes #466 
Some of our setup steps blindly pass all user-specified CLI args to `influxd print-config`. If `--help` or `-h` is in the args, `print-config` doesn't do what we expect, causing downstream failures.
This patch skips the steps that break when `--help` is requested, since they aren't needed to execute `--help`.
> Detect when --help is passed to influxdb and skip steps that break.

- telegraf/1.18/Dockerfile
- telegraf/1.18/alpine/Dockerfile
- telegraf/1.18/alpine/entrypoint.sh
- telegraf/1.18/entrypoint.sh
- telegraf/1.19/Dockerfile
- telegraf/1.19/alpine/Dockerfile
- telegraf/1.19/alpine/entrypoint.sh
- telegraf/1.19/entrypoint.sh
- telegraf/1.20/Dockerfile
- telegraf/1.20/alpine/Dockerfile
- telegraf/1.20/alpine/entrypoint.sh
- telegraf/1.20/entrypoint.sh
I ended up using su-exec on alpine because it's already packaged and easy to use. For debian I used setpriv because it is part of the utils-linux package which is an essential package on debian so it's already installed.
> Switch to su to run telegraf as non-root

- influxdb/2.0/alpine/entrypoint.sh
- influxdb/2.0/entrypoint.sh
- influxdb/2.1/alpine/entrypoint.sh
- influxdb/2.1/entrypoint.sh
Only bolt and engine files should be deleted on error, because the (engine) path may already exist beforehand and/or docker user may not have permissions to delete it.
Fixes helm charts issue [#350](https://github.com/influxdata/helm-charts/issues/350). In influxdb2 chart, engine path is mount path, permission error is logged and files are not deleted.
> fix: delete engine files only but not the path itself

- telegraf/1.18/Dockerfile
- telegraf/1.18/alpine/Dockerfile
- telegraf/1.18/alpine/entrypoint.sh
- telegraf/1.18/entrypoint.sh
- telegraf/1.19/Dockerfile
- telegraf/1.19/alpine/Dockerfile
- telegraf/1.19/alpine/entrypoint.sh
- telegraf/1.19/entrypoint.sh
- telegraf/1.20/Dockerfile
- telegraf/1.20/alpine/Dockerfile
- telegraf/1.20/alpine/entrypoint.sh
- telegraf/1.20/entrypoint.sh
- telegraf/nightly/Dockerfile
- telegraf/nightly/alpine/Dockerfile
- telegraf/nightly/alpine/entrypoint.sh
- telegraf/nightly/entrypoint.sh
The original fix does not play well with the official docker images build system (see moby/moby#40375, moby/moby#35699, moby/moby#1070). As a result, it was suggested to make these changes to the telegraf binary in the entrypoint script. (see docker-library/official-images#2432
Also adds +x to the nightly entrypoint scripts, which prevent it from getting executed during image launch. Noted this while testing these changes.
> telegraf: add NET_RAW and NET_BIND_SERVICE capabilities 

- telegraf/1.19/alpine/entrypoint.sh
- telegraf/1.19/entrypoint.sh
- telegraf/1.20/alpine/entrypoint.sh
- telegraf/1.20/entrypoint.sh
- telegraf/1.21/alpine/entrypoint.sh
- telegraf/1.21/entrypoint.sh
- telegraf/nightly/alpine/entrypoint.sh
- telegraf/nightly/entrypoint.sh
If a user specifies a different user to launch the telegraf container,
then the setcap command will fail since it needs to be run as root.
> fix: telegraf setcap command

- telegraf/1.19/alpine/entrypoint.sh
- telegraf/1.19/entrypoint.sh
- telegraf/1.20/alpine/entrypoint.sh
- telegraf/1.20/entrypoint.sh
- telegraf/1.21/alpine/entrypoint.sh
- telegraf/1.21/entrypoint.sh
- telegraf/nightly/alpine/entrypoint.sh
- telegraf/nightly/entrypoint.sh
The Telegraf container entrypoints attempt to use setcap to add
additional capabilites to the telegraf binary. Users who use aufs or run
a kernel that does not allow the setcap option will fail to start the
telegraf container as-is. This allows users to continue to use Telegraf,
but instead print an error message that setcap failed.
Resolves: #561
> fix: do not exit on failure of setcap on Telegraf

- influxdb/1.9/data/Dockerfile
- influxdb/1.9/data/alpine/Dockerfile
- influxdb/1.9/meta/Dockerfile
- influxdb/1.9/meta/alpine/Dockerfile
Does not contain OSS docker images.
> chore: release for plutonium 1.9.6

- .circleci/config.yml
Update to avoid potential CI issues mentioned in deprecated message in CircleCI.
> chore(ci): update image for VM based jobs

- influxdb/2.1/Dockerfile
- influxdb/2.1/alpine/Dockerfile
- influxdb/2.2/Dockerfile
- influxdb/2.2/alpine/Dockerfile
This fixes an issue where the `rm` command sporadically fails to remove files generated by `gpg`.
> chore: add more invocations of gpgconf --kill

- influxdb/1.9/data/alpine/Dockerfile
- influxdb/1.9/meta/alpine/Dockerfile
Changes:
1. Fix InfluxDB files path
Resolves: #613
> Fix 'influxd not found' error in InfluxDB 1.9.x images

- kapacitor/1.6/Dockerfile
- kapacitor/1.6/alpine/Dockerfile
Update to kappa 1.6.5, also bumps kappa's alpine version to 3.16
> chore(kapacitor): 1.6.5

- .circleci/config.yml
The previous version of the machine image and docker caused `apt` to fail while syncing repositories.
> chore: upgrade machine image and docker version

- telegraf/1.22/alpine/Dockerfile
- telegraf/1.23/alpine/Dockerfile
- telegraf/nightly/alpine/Dockerfile
In prep for Telegraf v1.24 in September, this updated the Alpine images for the supported images to 3.16. Telegraf v1.21 is not updated since it will be dropped as a part of the v1.24 release.
> chore: update telegraf alpine images to 3.16

- chronograf/1.10/Dockerfile
- chronograf/1.10/LICENSE
- chronograf/1.10/agpl-3.0.md
- chronograf/1.10/alpine/Dockerfile
- chronograf/1.10/alpine/LICENSE
- chronograf/1.10/alpine/agpl-3.0.md
- chronograf/1.10/alpine/entrypoint.sh
- chronograf/1.10/entrypoint.sh
- chronograf/1.6/Dockerfile
- chronograf/1.7/Dockerfile
- chronograf/1.8/Dockerfile
- chronograf/1.9/Dockerfile
This also upgrades Chronograf images from "stretch" to "bullseye". This is a requirement for releasing with Dockerhub. In one instance the "gpg" package was swapped with the "gnupg" virtual package. The virtual package pulls in "gpg" and "gpg-agent".
> chore: release chronograf 1.10.0

- telegraf/nightly/alpine/Dockerfile
We no longer produce a static specific package. All linux binaries are static on nightly images. v1.26.0 will be the first release with this as well.
> telegraf: use normal amd64 binary

- telegraf/nightly/alpine/Dockerfile
With v1.26.0, telegraf packages are built statically. As such we can now start building alpine images for more than just the amd64 package. We also no longer build the static package and update to the newest alpine.
> telegraf: allow for nightly arm64 images

- influxdb/2.1/entrypoint.sh
Currently when specifying `DOCKER_INFLUXDB_INIT_*` the config is created on the first run. On subsequent runs however this errors with
```
Error: config name "CONFIG" already exists
```
Since most users leave these variables defined, instead of trying to create the config again if it already exists, the config remains untouched and a warning is logged.
This fixes #542
> ignore init variables if config already exists

- influxdb/2.2/Dockerfile
- influxdb/2.2/alpine/Dockerfile
- influxdb/2.2/alpine/entrypoint.sh
- influxdb/2.2/entrypoint.sh
- influxdb/2.3/Dockerfile
- influxdb/2.3/alpine/Dockerfile
- influxdb/2.3/alpine/entrypoint.sh
- influxdb/2.3/entrypoint.sh
- influxdb/2.4/Dockerfile
- influxdb/2.4/alpine/Dockerfile
- influxdb/2.4/alpine/entrypoint.sh
- influxdb/2.4/entrypoint.sh
- influxdb/2.5/Dockerfile
- influxdb/2.5/alpine/Dockerfile
- influxdb/2.5/alpine/entrypoint.sh
- influxdb/2.5/entrypoint.sh
- influxdb/2.6/Dockerfile
- influxdb/2.6/alpine/Dockerfile
- influxdb/2.6/alpine/entrypoint.sh
- influxdb/2.6/entrypoint.sh
- influxdb/2.7/Dockerfile
- influxdb/2.7/alpine/Dockerfile
- influxdb/2.7/alpine/entrypoint.sh
- influxdb/2.7/entrypoint.sh
Unfortunately, it appeared that the `yq` hack didn't work with all scenarios. This replaces `jq` and `yq` with `dasel`. `dasel` can parse json, yaml, toml, xml and more. However, it has a few "rough edges" that the `jq` and `yq` implementation did not have. I'e broken this into two commits. The first commit contains changes in the `influxdb/2.4` directory. The second commit just copies the changes to most other `influxdb` directories.
> fix: correct toml parsing during initialization

- influxdb/2.2/entrypoint.sh
- influxdb/2.3/entrypoint.sh
- influxdb/2.4/entrypoint.sh
- influxdb/2.5/entrypoint.sh
- influxdb/2.6/entrypoint.sh
- influxdb/2.7/entrypoint.sh
fixes a simple copy-paste error for the init env var `DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE`
where the error kept mentioning `USERNAME_FILE` as opposed to `ADMIN_TOKEN_FILE`
closes #695
> fix(influxdbv2):  error msg for ADMIN_TOKEN_FILE

- telegraf/1.28/entrypoint.sh
- telegraf/1.29/entrypoint.sh
- telegraf/1.30/entrypoint.sh
- telegraf/nightly/entrypoint.sh
Based on upstream suggestion in https://github.com/docker-library/official-images/pull/16387 switches the sed parsing to for loop.
> telegraf: Switch from sed to for loop for parsing groups

- kapacitor/1.7/alpine/Dockerfile
- kapacitor/1.7/alpine/entrypoint.sh
- kapacitor/1.7/entrypoint.sh
Closes https://github.com/influxdata/edge/issues/598
Same solution as in #731 , with opt-out for running as root with env var `KAPACITOR_AS_ROOT=true`.
Kapacitor does not require access to protected/system resources that might be limited when running as non-root. Inputs & outputs are done via http/TCP/UDP/filesystem. The documentation does not mention requiring any special permission. Non-docker installation from package runs as `kapacitord` as `kapacitor` user, and `kapacitord` does not have suid set.
Tested:
> feat: allow running kapacitor as non-root

- chronograf/1.10/alpine/Dockerfile
- chronograf/1.7/alpine/Dockerfile
- chronograf/1.8/alpine/Dockerfile
- chronograf/1.9/alpine/Dockerfile
- influxdb/1.10/meta/alpine/Dockerfile
- influxdb/1.11/meta/alpine/Dockerfile
- influxdb/1.8/meta/alpine/Dockerfile
- influxdb/1.9/meta/alpine/Dockerfile
- influxdb/2.7/alpine/Dockerfile
- kapacitor/1.6/alpine/Dockerfile
- kapacitor/1.7/alpine/Dockerfile
- telegraf/1.28/alpine/Dockerfile
- telegraf/1.29/alpine/Dockerfile
- telegraf/1.30/alpine/Dockerfile
- telegraf/nightly/alpine/Dockerfile
This only updates images that are actually posted on Dockerhub, versions that are too old or no loner there are not updated.
resolves #745
> feat: Update all images to use alpine:3 versus specific version

- chronograf/1.10/alpine/Dockerfile
- chronograf/1.7/alpine/Dockerfile
- chronograf/1.8/alpine/Dockerfile
- chronograf/1.9/alpine/Dockerfile
- influxdb/1.10/meta/alpine/Dockerfile
- influxdb/1.11/meta/alpine/Dockerfile
- influxdb/1.8/meta/alpine/Dockerfile
- influxdb/1.9/meta/alpine/Dockerfile
- influxdb/2.7/alpine/Dockerfile
- kapacitor/1.6/alpine/Dockerfile
- kapacitor/1.7/alpine/Dockerfile
- telegraf/1.28/alpine/Dockerfile
- telegraf/1.29/alpine/Dockerfile
- telegraf/1.30/alpine/Dockerfile
Per upstream Docker, they would prefer we stay with a specific minor release to avoid breaking changes. Instead of updating as soon as a new Alpine image is out, they would rather we specifically choose to update due to past experiences.
See https://github.com/docker-library/official-images/pull/16888
> chore: Update Alpine images to 3.20

- influxdb/3.0-core/Dockerfile
- influxdb/3.0-enterprise/Dockerfile
I tested this locally by building the images, and starting them to check that they report the correct version.
Build the docker image:
```
cd influxdb/3.0-core
docker build -t "influxdb:core" .
```
Run the server with port `8181` exposed:
```
docker run -p 8181:8181 influxdb:core --node-id test --object-store memory --without-auth
```
Ping the server:
```
curl localhost:8181/ping
```
Gets the response:
```json
{"version":"3.0.2","revision":"d80d6cd600","process_id":"c3810409-51b6-4912-93f5-b663e399f2f3"}
```
Performed similar steps for Enterprise.
> chore: update core and enterprise to 3.0.2

- influxdb/3.2-core/Dockerfile
- influxdb/3.2-core/entrypoint.sh
- influxdb/3.2-enterprise/Dockerfile
- influxdb/3.2-enterprise/entrypoint.sh
Added 3.2.0-core and 3.2.0-enterprise. The plan is, this version will be tested till Monday next week and a final switch over to this release will be done Monday next week.
By merging this PR I'm assuming we can run `docker pull influxdb3:3.2.0-enterprise`. It is not clear if this will work only after updating the manifest as well. Also, I don't want to update the latest tag as we want to run controlled test till Monday. If my assumptions are incorrect please advise what steps to take or amendments to make to this PR.
> chore: create 3.2.0 release artefacts

- chronograf/1.10/alpine/Dockerfile
- chronograf/1.10/alpine/entrypoint.sh
In `Dockerfile` and in `entrypoint.sh` replace `su-exec` with `setpriv`, as one already done for kapacitor in PR #814
> chore: remove su-exec from chronograf

- chronograf/1.10/Dockerfile
- chronograf/1.10/alpine/Dockerfile
- influxdb/1.10/data/Dockerfile
- influxdb/1.10/data/alpine/Dockerfile
- influxdb/1.10/meta/Dockerfile
- influxdb/1.10/meta/alpine/Dockerfile
- influxdb/1.11/Dockerfile
- influxdb/1.11/alpine/Dockerfile
- influxdb/1.11/data/Dockerfile
- influxdb/1.11/data/alpine/Dockerfile
- influxdb/1.11/meta/Dockerfile
- influxdb/1.11/meta/alpine/Dockerfile
- influxdb/1.12/Dockerfile
- influxdb/1.12/alpine/Dockerfile
- influxdb/1.12/data/Dockerfile
- influxdb/1.12/data/alpine/Dockerfile
- influxdb/1.12/meta/Dockerfile
- influxdb/1.12/meta/alpine/Dockerfile
- influxdb/2.7/Dockerfile
- influxdb/2.7/alpine/Dockerfile
- influxdb/3.4-core/Dockerfile
- influxdb/3.4-enterprise/Dockerfile
- kapacitor/1.8/Dockerfile
- kapacitor/1.8/alpine/Dockerfile
- telegraf/1.34/Dockerfile
- telegraf/1.34/alpine/Dockerfile
- telegraf/1.35/Dockerfile
- telegraf/1.35/alpine/Dockerfile
- telegraf/1.36/Dockerfile
- telegraf/1.36/alpine/Dockerfile
https://repos.influxdata.com/ hosts two different keys:
* influxdata-archive.key
* influxdata-archive_compat.key
and the Dockerfiles in this repo specify the fingerprint of influxdata-archive_compat.key. This key expires in January 2026. Update the Dockerfiles to instead fetch the fingerprint of influxdata-archive.key (which uses signing subkeys) since our rotation processes will add the new signing subkey to this file (leaving the old, expired ones). Put another way, by updating to use influxdata-archive.key, we won't have to worry about changing these Dockerfiles when we periodically rotate.
Importantly, the influxdata-archive_compat.key is the extracted signing subkey from influxdata-archive.key. As such, the above change doesn't change anything wrt which signing key is being used to …
> chore: update GPG to use the non-compat key
