influxdb/1.1/alpine/influxdb.conf, influxdb/1.1/influxdb.conf
=> Remove the section in the default configuration file that enables the admin console

kapacitor/1.1/alpine/kapacitor.conf, kapacitor/1.1/kapacitor.conf
=> Fix kapacitor.conf storage section to use the correct config key

kapacitor/1.2/alpine/Dockerfile, telegraf/1.2/Dockerfile, telegraf/1.2/alpine/Dockerfile, telegraf/1.2/alpine/entrypoint.sh, telegraf/1.2/entrypoint.sh
Upgrade kapacitor 1.2.0-rc1-alpine to alpine:3.5.
=> telegraf 1.2.0 rc1

kapacitor/1.1/alpine/Dockerfile, kapacitor/1.2/alpine/Dockerfile
=> Ensure ca-certificates stay installed for the kapacitor alpine images

telegraf/1.3/Dockerfile, telegraf/1.3/alpine/Dockerfile
=> telegraf 1.3.3

circle-test.sh, influxdb/1.2/Dockerfile, influxdb/1.2/alpine/Dockerfile, influxdb/1.2/alpine/entrypoint.sh, influxdb/1.2/alpine/init-influxdb.sh, influxdb/1.2/entrypoint.sh, influxdb/1.2/init-influxdb.sh, influxdb/1.3/Dockerfile, influxdb/1.3/alpine/Dockerfile, influxdb/1.3/alpine/entrypoint.sh, influxdb/1.3/alpine/init-influxdb.sh, influxdb/1.3/entrypoint.sh, influxdb/1.3/init-influxdb.sh, influxdb/circle-test.sh, influxdb/nightly/Dockerfile, influxdb/nightly/alpine/Dockerfile, influxdb/nightly/alpine/entrypoint.sh, influxdb/nightly/alpine/init-influxdb.sh, influxdb/nightly/entrypoint.sh, influxdb/nightly/init-influxdb.sh
Includes support for custom .sh-scripts and .iql-files on influxdb
initialization.
=> Added the possibility to initialize influxdb

influxdb/1.2/alpine/entrypoint.sh, influxdb/1.3/alpine/entrypoint.sh
=> The alpine influxdb images use bash only syntax

chronograf/manifest.json, influxdb/manifest.json, kapacitor/manifest.json, telegraf/1.3/Dockerfile, telegraf/1.4/Dockerfile, telegraf/manifest.json, update.go
Thanks to @longquan7 for the original Dockerfiles and @jcberthon for the
follow up code to support 32-bit arm architectures.
=> Add support for all arm32v6, arm32v7, and arm64v8 in telegraf

telegraf/1.5/Dockerfile, telegraf/1.5/alpine/Dockerfile, telegraf/1.5/alpine/entrypoint.sh, telegraf/1.5/entrypoint.sh, telegraf/manifest.json
New minor release, but no major changes to how Telegraf is ran.
=> Telegraf 1.5.0

chronograf/1.7/Dockerfile, chronograf/1.7/LICENSE, chronograf/1.7/agpl-3.0.md, chronograf/1.7/alpine/Dockerfile, chronograf/1.7/alpine/LICENSE, chronograf/1.7/alpine/agpl-3.0.md, chronograf/1.7/alpine/entrypoint.sh, chronograf/1.7/entrypoint.sh, chronograf/manifest.json, influxdb/1.7/Dockerfile, influxdb/1.7/alpine/Dockerfile, influxdb/1.7/alpine/entrypoint.sh, influxdb/1.7/alpine/influxdb.conf, influxdb/1.7/alpine/init-influxdb.sh, influxdb/1.7/entrypoint.sh, influxdb/1.7/influxdb.conf, influxdb/1.7/init-influxdb.sh, influxdb/manifest.json
There is no 1.7.0 release for the enterprise product at the moment so it
does not have a 1.7.0.
=> chronograf 1.7.0 and influxdb 1.7.0

chronograf/1.7/Dockerfile
=> chronograf-1.7.9

influxdb/1.5/alpine/init-influxdb.sh, influxdb/1.5/data/alpine/init-influxdb.sh, influxdb/1.5/data/init-influxdb.sh, influxdb/1.5/init-influxdb.sh, influxdb/1.6/alpine/init-influxdb.sh, influxdb/1.6/data/alpine/init-influxdb.sh, influxdb/1.6/data/init-influxdb.sh, influxdb/1.6/init-influxdb.sh, influxdb/1.7/alpine/init-influxdb.sh, influxdb/1.7/data/alpine/init-influxdb.sh, influxdb/1.7/data/init-influxdb.sh, influxdb/1.7/init-influxdb.sh, influxdb/nightly/alpine/init-influxdb.sh, influxdb/nightly/init-influxdb.sh
Fixing init script where setting INFLUXDB_META_DIR causes initialization to run every time the container restarts #216
=> fix bug from issue#216

kapacitor/1.5/Dockerfile, kapacitor/1.5/alpine/Dockerfile
=> feat(kapa): kapa 1.5.4

chronograf/1.8/Dockerfile, chronograf/1.8/alpine/Dockerfile
=> chore: chronograf-1.8.2

chronograf/1.6/alpine/Dockerfile, chronograf/1.7/alpine/Dockerfile, chronograf/1.8/alpine/Dockerfile, influxdb/1.7/alpine/Dockerfile, influxdb/1.7/data/alpine/Dockerfile, influxdb/1.7/meta/alpine/Dockerfile, influxdb/1.8/alpine/Dockerfile, influxdb/1.8/data/alpine/Dockerfile, influxdb/1.8/meta/alpine/Dockerfile, influxdb/nightly/alpine/Dockerfile, kapacitor/1.4/alpine/Dockerfile, kapacitor/1.5/alpine/Dockerfile, telegraf/1.13/alpine/Dockerfile, telegraf/1.14/alpine/Dockerfile
Fix https://github.com/influxdata/influxdata-docker/issues/366
=> Upgrading all instances of alpine:3.9 to 3.12

chronograf/1.6/Dockerfile, chronograf/1.6/alpine/Dockerfile, chronograf/1.7/Dockerfile, chronograf/1.7/alpine/Dockerfile, chronograf/1.8/Dockerfile, chronograf/1.8/alpine/Dockerfile, influxdb/1.7/Dockerfile, influxdb/1.7/alpine/Dockerfile, influxdb/1.7/data/Dockerfile, influxdb/1.7/data/alpine/Dockerfile, influxdb/1.7/meta/Dockerfile, influxdb/1.7/meta/alpine/Dockerfile, influxdb/1.8/Dockerfile, influxdb/1.8/alpine/Dockerfile, kapacitor/1.4/Dockerfile, kapacitor/1.4/alpine/Dockerfile, kapacitor/1.5/Dockerfile
This is a fix for a GPG bug causing a flakey error in the build system.
=> fix: workaround for gpg bug

kapacitor/1.5/alpine/Dockerfile, telegraf/1.13/Dockerfile, telegraf/1.14/alpine/Dockerfile, telegraf/1.15/Dockerfile, telegraf/1.15/alpine/Dockerfile
This is a fix for fot some gpg build failures in telegraf.  This is a workaround for a bug in gpg.
=> fix: telegraf gpg build failures

kapacitor/1.5/Dockerfile, kapacitor/1.5/alpine/Dockerfile
=> chore: update kapacitor 1.5.7

kapacitor/1.5/Dockerfile, kapacitor/1.5/alpine/Dockerfile
=> chore: kapacitor to 1.5.8

influxdb/2.0/Dockerfile, influxdb/2.0/alpine/Dockerfile
Update the nightly download links to instead pull the release binary
=> InfluxDB 2.0.4

influxdb/2.0/alpine/Dockerfile, influxdb/2.0/alpine/entrypoint.sh, influxdb/2.0/entrypoint.sh
See the review comments from docker-library/official-images#9594
=> Address points from DockerHub review

influxdb/2.0/alpine/Dockerfile, influxdb/2.0/alpine/entrypoint.sh, influxdb/2.0/entrypoint.sh
See review comments here: https://github.com/docker-library/official-images/pull/9594#issuecomment-777149713
I verified that the `gosu` change matches the behavior of other official DB images like `postgres` and `mongo`
=> Address DockerHub review

influxdb/2.0/Dockerfile, influxdb/2.0/alpine/Dockerfile, influxdb/2.0/alpine/entrypoint.sh, influxdb/2.0/entrypoint.sh
Addressing the parting review from https://github.com/docker-library/official-images/pull/9594#issuecomment-785335914
=> Address final DockerHub review on InfluxDB 2.0.4

influxdb/1.7/Dockerfile, influxdb/1.7/alpine/Dockerfile, influxdb/1.7/data/Dockerfile, influxdb/1.7/data/alpine/Dockerfile, influxdb/1.7/meta/Dockerfile, influxdb/1.7/meta/alpine/Dockerfile
This reverts commit aa907bd9b8c712f147beebc548697ad8bc9348c5.
=> Revert "chore: update 1.7 branch to 1.7.11"

influxdb/1.9/data/Dockerfile, influxdb/1.9/data/alpine/Dockerfile, influxdb/1.9/meta/Dockerfile, influxdb/1.9/meta/alpine/Dockerfile
Release of Docker images for Enterprise-only v1.9.3 InfluxDB
=> InfluxDB v1.9.3 Enterprise-only

kapacitor/1.6/Dockerfile, kapacitor/1.6/alpine/Dockerfile, kapacitor/1.6/alpine/entrypoint.sh, kapacitor/1.6/alpine/kapacitor.conf, kapacitor/1.6/entrypoint.sh, kapacitor/1.6/kapacitor.conf
This adds a 1.6 folder for kappa and adds Kappa 1.6.1
=> chore: upgrade kapa to 1.6.1

chronograf/1.8/Dockerfile, chronograf/1.8/alpine/Dockerfile
=> Chronograf v1.8.10

chronograf/1.9/Dockerfile, chronograf/1.9/LICENSE, chronograf/1.9/agpl-3.0.md, chronograf/1.9/alpine/Dockerfile, chronograf/1.9/alpine/LICENSE, chronograf/1.9/alpine/agpl-3.0.md, chronograf/1.9/alpine/entrypoint.sh, chronograf/1.9/entrypoint.sh, chronograf/manifest.json
=> Chronograf v1.9.0

.circleci/config.yml, influxdb/2.1/Dockerfile, influxdb/2.1/alpine/Dockerfile, influxdb/2.1/alpine/default-config.yml, influxdb/2.1/alpine/entrypoint.sh, influxdb/2.1/default-config.yml, influxdb/2.1/entrypoint.sh, influxdb/test/test-2x-e2e.sh
Closes #534
For now the `2.1` builds pull down `2.0.9` of the server and `2.1.1` of the CLI. Once v2.1 of the server is released, this PR should be updated.
=> Init 2.1 build of InfluxDB

telegraf/nightly/Dockerfile, telegraf/nightly/alpine/Dockerfile, telegraf/nightly/alpine/entrypoint.sh, telegraf/nightly/entrypoint.sh
Add a new directory in the Telegraf docker folder that downloads from the nightly binaries.
=> Add Telegraf nightly dockerfiles

telegraf/1.18/Dockerfile, telegraf/1.18/alpine/Dockerfile, telegraf/1.19/Dockerfile, telegraf/1.19/alpine/Dockerfile, telegraf/1.20/Dockerfile, telegraf/1.20/alpine/Dockerfile, telegraf/nightly/Dockerfile, telegraf/nightly/alpine/Dockerfile
=> telegraf: add CAP_NET_RAW and NET_BIND_SERVICE capabilities

chronograf/1.9/Dockerfile, chronograf/1.9/alpine/Dockerfile, chronograf/manifest.json
=> Chronograf 1.9.3

influxdb/2.1/Dockerfile
=> Fixed typo in Dockerfile comment

.circleci/config.yml, influxdb/2.2/Dockerfile, influxdb/2.2/alpine/Dockerfile, influxdb/2.2/alpine/default-config.yml, influxdb/2.2/alpine/entrypoint.sh, influxdb/2.2/default-config.yml, influxdb/2.2/entrypoint.sh
This copies the files from influxdb/2.1 into influxdb/2.2 and updates INFLUXDB_VERSION to 2.2.0.
=> chore: release influxdb 2.2.0

influxdb/2.0/alpine/Dockerfile, influxdb/2.0/alpine/entrypoint.sh
https://github.com/ncopa/su-exec#why-reinvent-gosu
=> Use su-exec on Alpine

influxdb/1.10/data/alpine/Dockerfile, influxdb/1.10/meta/alpine/Dockerfile, influxdb/1.8/alpine/Dockerfile, influxdb/1.8/data/alpine/Dockerfile, influxdb/1.8/meta/alpine/Dockerfile, influxdb/1.9/data/alpine/Dockerfile, influxdb/1.9/meta/alpine/Dockerfile, influxdb/2.4/alpine/Dockerfile, influxdb/2.5.1/alpine/Dockerfile, influxdb/2.5/alpine/Dockerfile, influxdb/2.6/alpine/Dockerfile
=> influxdb: update alpine images to 3.17

influxdb/2.2/entrypoint.sh, influxdb/2.3/entrypoint.sh, influxdb/2.4/entrypoint.sh, influxdb/2.5/entrypoint.sh, influxdb/2.6/entrypoint.sh
Adds support for Docker Secret token file by using DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE env variable
=> Support for ADMIN_TOKEN docker secret

influxdb/2.2/Dockerfile, influxdb/2.2/alpine/Dockerfile, influxdb/2.3/Dockerfile, influxdb/2.3/alpine/Dockerfile, influxdb/2.4/Dockerfile, influxdb/2.4/alpine/Dockerfile, influxdb/2.5/Dockerfile, influxdb/2.5/alpine/Dockerfile, influxdb/2.6/Dockerfile, influxdb/2.6/alpine/Dockerfile
This should resolve everything that was mentioned in https://github.com/docker-library/official-images/pull/14225.
=> chore: implement feedback from docker-library maintainer

telegraf/nightly/entrypoint.sh
=> fix: Respect user supplied groups for Telegraf

telegraf/1.27/entrypoint.sh, telegraf/1.28/entrypoint.sh, telegraf/1.29/entrypoint.sh
=> fix(telegraf): Ensure groups passed to container are applied

chronograf/1.10/alpine/Dockerfile, chronograf/1.10/alpine/entrypoint.sh, chronograf/1.10/entrypoint.sh
Closes https://github.com/influxdata/edge/issues/596
=> feat: run Chronograf as non-root

influxdb/1.10/data/alpine/Dockerfile, influxdb/1.11/data/alpine/Dockerfile
Previous PR missed the data nodes and only got the meta nodes.
=> Update data node alpine images

influxdb/2.7/Dockerfile, influxdb/2.7/alpine/Dockerfile, influxdb/test/.gitignore
* Add .idea to gitignore so it will not get committed
=> feat: Add 2.7.12 as influxdb version

influxdb/3.2-core/Dockerfile, influxdb/3.2-enterprise/Dockerfile
=> chore: influxdb3 3.2.1 release

influxdb/1.11/data/Dockerfile, influxdb/1.11/data/alpine/Dockerfile, influxdb/1.11/meta/Dockerfile, influxdb/1.11/meta/alpine/Dockerfile
Updating only data and meta Docker files, not OSS
=> chore: Update for release InfluxDB enterprise 1.11.9

influxdb/3.5-core/Dockerfile, influxdb/3.5-core/entrypoint.sh, influxdb/3.5-enterprise/Dockerfile, influxdb/3.5-enterprise/entrypoint.sh
=> chore: release 3.5.0
